alert("Hello to the page")
confirm("do you want to go in???")
var inp = prompt("Enter your number")
document.write(`${inp} x 1 =` , inp*1 + "<br>")
document.write(`${inp} x 2 = `, inp*2 + "<br>")
document.write(`${inp} x 3 = `, inp*3 + "<br>")
document.write(`${inp} x 4 = `, inp*4 + "<br>")
document.write(`${inp} x 5 = `, inp*5 + "<br>")
document.write(`${inp} x 6 = `, inp*6 + "<br>")
document.write(`${inp} x 7 = `, inp*7 + "<br>")
document.write(`${inp} x 8 = `, inp*8 + "<br>")
document.write(`${inp} x 9 = `, inp*9 + "<br>")
document.write(`${inp} x 10 = `, inp*10 + "<br>")
document.write(`${inp} x 11 = `, inp*11 + "<br>")
document.write(`${inp} x 12 = `, inp*12 + "<br>")
document.write(`${inp} x 13 = `, inp*13 + "<br>")
document.write(`${inp} x 14 = `, inp*14 + "<br>")
document.write(`${inp} x 15 = `, inp*15 + "<br>")
document.write(`${inp} x 16 = `, inp*16 + "<br>")
document.write(`${inp} x 17 = `, inp*17 + "<br>")
document.write(`${inp} x 18 = `, inp*18 + "<br>")
document.write(`${inp} x 19 = `, inp*19 + "<br>")
document.write(`${inp} x 20 = `, inp*20 + "<br>")